driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
    run_list: apt::default
  - name: debian-8.6
    run_list: apt::default
  - name: fedora-25
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default
  - name: freebsd-9.3
  - name: freebsd-10.3

suites:
  - name: default
    run_list:
      - recipe[bluepill_test]
    attributes: {bluepill: { bin: "/opt/chef/embedded/bin/bluepill" } }
