driver:
  name: vagrant

provisioner:
  name: chef_zero

driver_config:
  require_chef_omnibus: true

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: fedora-21
  - name: ubuntu-12.04
    run_list:
    - recipe[apt::default]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[minitest-handler]
      - recipe[bluepill_test]
    attributes: {bluepill: { bin: "/opt/chef/embedded/bin/bluepill" } }
